rosbag2_recorder:
  ros__parameters:

    use_sim_time: false

    record:
      all_topics: false
      topics: ["/camera/image_raw"]

      all_services: true

    storage:
      uri: "/bags/camera"
      storage_id: "mcap"
      max_cache_size: 0
