recorder:
  ros__parameters:
    use_sim_time: false
    bag_uri: /tmp/rosbag2_0
    topic_names: '/camera/image_raw'

picamera_ros2:
  ros__parameters:
    video_width: 640
    video_heigh: 480
    framerate: 20
    shutter: 1000.0
    hdr: false
    verbose: false
