recorder:
  ros__parameters:
    use_sim_time: false
    
    image_topic_name: '/camera/image_raw'
    px4_mode_topic_name: "/fmu/out/vehicle_state"
    interception_mode_topic_name: "/interception/state"

    px4_record_state: 14 # 14: OFFBOARD, 0: MANUAL
    interception_record_state: "INTERCEPT"

camera:
  ros__parameters:
    video_width: 640
    video_heigh: 480
    framerate: 20
    shutter: 1000.0
    hdr: false
    verbose: false
    publish_grayscale_image: false
