recorder:
  ros__parameters:
    use_sim_time: false
    topic_names: '/camera/image_raw'
    state_topic_name: "/fmu/out/vehicle_state"
    recording_state: 14 # 14: OFFBOARD, 0: MANUAL

camera:
  ros__parameters:
    video_width: 640
    video_heigh: 480
    framerate: 20
    shutter: 1000.0
    hdr: false
    verbose: false
    publish_grayscale_image: false
